import { mkdirSync, writeFileSync } from "node:fs";
import * as path from "node:path";

import { snakeToLowerCamel } from "../util/case.js";

export interface EmitCommandsResult {
  swiftPath: string;
  count: number;
}

/**
 * 31 request-type discriminants the QVAC worker dispatches on. Curated
 * from `tetherto/qvac/packages/sdk/server/rpc/handler-registry.ts:75-158`
 * (verified at commit 9db6f98). These are the JSON `request.type` values
 * the wire actually carries; bare-rpc's numeric `command` field is a
 * per-call counter and not the routing key.
 *
 * The full table + mode classification (reply/stream/duplex) is in
 * `docs/qvac-sdk-internals.md` §6.
 */
const QVAC_COMMAND_TYPES: ReadonlyArray<{
  wire: string;
  mode: "reply" | "stream" | "duplex";
  comment: string;
}> = [
  { wire: "heartbeat", mode: "reply", comment: "" },
  { wire: "loadModel", mode: "reply", comment: "supports progress streaming" },
  { wire: "unloadModel", mode: "reply", comment: "" },
  { wire: "embed", mode: "reply", comment: "" },
  { wire: "cancel", mode: "reply", comment: "" },
  { wire: "provide", mode: "reply", comment: "" },
  { wire: "stopProvide", mode: "reply", comment: "" },
  { wire: "deleteCache", mode: "reply", comment: "" },
  { wire: "getModelInfo", mode: "reply", comment: "" },
  { wire: "getLoadedModelInfo", mode: "reply", comment: "" },
  { wire: "pluginInvoke", mode: "reply", comment: "" },
  { wire: "modelRegistryList", mode: "reply", comment: "" },
  { wire: "modelRegistrySearch", mode: "reply", comment: "" },
  { wire: "modelRegistryGetModel", mode: "reply", comment: "" },
  { wire: "suspend", mode: "reply", comment: "" },
  { wire: "resume", mode: "reply", comment: "" },
  { wire: "state", mode: "reply", comment: "" },
  { wire: "downloadAsset", mode: "reply", comment: "supports progress streaming" },
  { wire: "rag", mode: "reply", comment: "supports progress streaming for ingest/saveEmbeddings/reindex" },
  { wire: "finetune", mode: "reply", comment: "supports progress streaming for start/resume" },
  { wire: "transcribe", mode: "stream", comment: "" },
  { wire: "loggingStream", mode: "stream", comment: "" },
  { wire: "translate", mode: "stream", comment: "" },
  { wire: "textToSpeech", mode: "stream", comment: "" },
  { wire: "ocrStream", mode: "stream", comment: "" },
  { wire: "diffusionStream", mode: "stream", comment: "" },
  { wire: "upscaleStream", mode: "stream", comment: "" },
  { wire: "pluginInvokeStream", mode: "stream", comment: "" },
  { wire: "completionStream", mode: "stream", comment: "" },
  { wire: "transcribeStream", mode: "duplex", comment: "" },
  { wire: "textToSpeechStream", mode: "duplex", comment: "" },
];

export function emitCommands(input: { source: string }, outDir: string): EmitCommandsResult {
  mkdirSync(outDir, { recursive: true });
  const swiftPath = path.join(outDir, "Commands.swift");

  // Sort alphabetically by Swift case name for deterministic output.
  const sorted = [...QVAC_COMMAND_TYPES].sort((a, b) =>
    a.wire < b.wire ? -1 : a.wire > b.wire ? 1 : 0,
  );

  const out: string[] = [];
  out.push("// Auto-generated by scripts/codegen — DO NOT EDIT BY HAND.");
  out.push(`// Source: ${input.source}`);
  out.push("// Curated from packages/sdk/server/rpc/handler-registry.ts:75-158");
  out.push("// Re-generate with: pnpm --filter @qvac-swift/codegen run run");
  out.push("");
  out.push("import Foundation");
  out.push("");
  out.push("/// Wire-level dispatch mode for each `QVACCommand`. Mirrors the");
  out.push("/// `handler-registry.ts` entry's `type` field (`reply`, `stream`,");
  out.push("/// or `duplex`) and tells the client which `RPCBridge` primitive");
  out.push("/// to use: `send()` for reply, `streamResponse()` for stream, the");
  out.push("/// bidirectional pair for duplex.");
  out.push("public enum QVACCommandMode: String, Sendable, Equatable, CaseIterable {");
  out.push("  case reply");
  out.push("  case stream");
  out.push("  case duplex");
  out.push("}");
  out.push("");

  out.push("/// All 31 request types the QVAC Bare worker dispatches on.");
  out.push("/// Routed by the JSON envelope's `type` field, not by bare-rpc's");
  out.push("/// numeric `command` (which is a per-call counter — see");
  out.push("/// `docs/qvac-sdk-internals.md` §6).");
  out.push("public enum QVACCommand: String, Sendable, Equatable, CaseIterable {");
  for (const c of sorted) {
    const swift = snakeToLowerCamel(c.wire);
    if (c.comment) {
      out.push(`  /// ${c.comment}`);
    }
    if (swift === c.wire) {
      out.push(`  case ${swift}`);
    } else {
      out.push(`  case ${swift} = "${c.wire}"`);
    }
  }
  out.push("");
  out.push("  /// Wire-level dispatch mode. Stable per-command.");
  out.push("  public var mode: QVACCommandMode {");
  out.push("    switch self {");
  for (const c of sorted) {
    const swift = snakeToLowerCamel(c.wire);
    out.push(`    case .${swift}: return .${c.mode}`);
  }
  out.push("    }");
  out.push("  }");
  out.push("}");
  out.push("");

  writeFileSync(swiftPath, out.join("\n") + "\n", "utf-8");
  return { swiftPath, count: sorted.length };
}
