import { mkdirSync, writeFileSync } from "node:fs";
import * as path from "node:path";

import { snakeToLowerCamel } from "../util/case.js";

export interface EmitErrorsInput {
  /** SDK_CLIENT_ERROR_CODES contents (name -> numeric code). */
  clientCodes: Record<string, number>;
  /** SDK_SERVER_ERROR_CODES contents. */
  serverCodes: Record<string, number>;
  /** package name (`@qvac/sdk`). */
  packageName: string;
  /** package version (e.g. `0.10.2`). */
  packageVersion: string;
  /** Optional commit / source URL string for the header comment. */
  sourceLine?: string;
}

export interface EmitErrorsResult {
  swiftPath: string;
  metaPath: string;
  clientCount: number;
  serverCount: number;
}

/**
 * Load `SDK_CLIENT_ERROR_CODES` and `SDK_SERVER_ERROR_CODES` from the npm
 * package via dynamic import. Returns the constants verbatim — the caller
 * passes them straight to `emitErrorCodes`.
 */
export async function loadErrorCodesFromPackage(): Promise<{
  clientCodes: Record<string, number>;
  serverCodes: Record<string, number>;
}> {
  const sdk = (await import("@qvac/sdk")) as {
    SDK_CLIENT_ERROR_CODES?: Record<string, number>;
    SDK_SERVER_ERROR_CODES?: Record<string, number>;
  };
  if (!sdk.SDK_CLIENT_ERROR_CODES || !sdk.SDK_SERVER_ERROR_CODES) {
    throw new Error(
      "@qvac/sdk does not export SDK_CLIENT_ERROR_CODES / SDK_SERVER_ERROR_CODES — has the API changed?",
    );
  }
  return {
    clientCodes: { ...sdk.SDK_CLIENT_ERROR_CODES },
    serverCodes: { ...sdk.SDK_SERVER_ERROR_CODES },
  };
}

/**
 * Emit `<outDir>/ErrorCodes.swift` and `<outDir>/ErrorCodes.json`.
 * Sort everything by numeric code so re-runs are bit-identical.
 */
export function emitErrorCodes(
  input: EmitErrorsInput,
  outDir: string,
): EmitErrorsResult {
  mkdirSync(outDir, { recursive: true });

  const sortedClient = sortByCode(input.clientCodes);
  const sortedServer = sortByCode(input.serverCodes);

  const out: string[] = [];
  out.push("// Auto-generated by scripts/codegen — DO NOT EDIT BY HAND.");
  out.push(`// Source: ${input.packageName}@${input.packageVersion}`);
  if (input.sourceLine) out.push(`// ${input.sourceLine}`);
  out.push("// Re-generate with: pnpm --filter @qvac-swift/codegen run run");
  out.push("");
  out.push("import Foundation");
  out.push("");

  out.push("/// High-level grouping for `QVACError`.");
  out.push("public enum QVACErrorCategory: String, Sendable, Equatable, CaseIterable {");
  out.push("  case client");
  out.push("  case server");
  out.push("  case transport");
  out.push("  case unknown");
  out.push("}");
  out.push("");

  out.push("/// Top-level error emitted by `QVACClient`.");
  out.push("///");
  out.push("/// - `client(code, message)`: numeric range 50,001–52,000. Originates");
  out.push("///   inside the SDK client *before* the worker dispatches the request.");
  out.push("/// - `server(code, message)`: numeric range 52,001–54,000. Emitted by");
  out.push("///   the Bare worker and serialized on the wire as");
  out.push("///   `{ type: \"error\", code, name, message, ... }`.");
  out.push("/// - `transport(...)`: framing- or socket-layer failures local to Swift.");
  out.push("/// - `unknown(...)`: any wire code that doesn't match a generated case.");
  out.push("///   Used for forward compatibility — a newer worker can introduce new");
  out.push("///   codes without breaking older clients.");
  out.push("public enum QVACError: Error, Sendable, Equatable {");
  out.push("  case client(QVACClientErrorCode, message: String)");
  out.push("  case server(QVACServerErrorCode, message: String)");
  out.push("  case transport(QVACTransportError)");
  out.push("  case unknown(code: Int?, name: String?, message: String)");
  out.push("");
  out.push("  public var category: QVACErrorCategory {");
  out.push("    switch self {");
  out.push("    case .client: return .client");
  out.push("    case .server: return .server");
  out.push("    case .transport: return .transport");
  out.push("    case .unknown: return .unknown");
  out.push("    }");
  out.push("  }");
  out.push("");
  out.push("  public var wireCode: Int? {");
  out.push("    switch self {");
  out.push("    case .client(let c, _): return c.rawValue");
  out.push("    case .server(let c, _): return c.rawValue");
  out.push("    case .transport: return nil");
  out.push("    case .unknown(let c, _, _): return c");
  out.push("    }");
  out.push("  }");
  out.push("");
  out.push("  public var wireName: String? {");
  out.push("    switch self {");
  out.push("    case .client(let c, _): return c.wireName");
  out.push("    case .server(let c, _): return c.wireName");
  out.push("    case .transport(let t): return t.wireName");
  out.push("    case .unknown(_, let n, _): return n");
  out.push("    }");
  out.push("  }");
  out.push("");
  out.push("  public var message: String {");
  out.push("    switch self {");
  out.push("    case .client(_, let m): return m");
  out.push("    case .server(_, let m): return m");
  out.push("    case .transport(let t): return t.message");
  out.push("    case .unknown(_, _, let m): return m");
  out.push("    }");
  out.push("  }");
  out.push("");
  out.push("  /// Decode an error frame's `(code, name, message)` triple into a typed");
  out.push("  /// `QVACError`. Unknown codes fall through to `.unknown(...)` rather");
  out.push("  /// than throwing — forward compat with newer workers.");
  out.push("  public init(wireCode: Int?, name: String?, message: String) {");
  out.push("    if let code = wireCode {");
  out.push("      if let c = QVACClientErrorCode(rawValue: code) {");
  out.push("        self = .client(c, message: message)");
  out.push("        return");
  out.push("      }");
  out.push("      if let s = QVACServerErrorCode(rawValue: code) {");
  out.push("        self = .server(s, message: message)");
  out.push("        return");
  out.push("      }");
  out.push("    }");
  out.push("    self = .unknown(code: wireCode, name: name, message: message)");
  out.push("  }");
  out.push("}");
  out.push("");

  out.push("extension QVACError: LocalizedError {");
  out.push("  public var errorDescription: String? {");
  out.push("    let prefix: String");
  out.push("    switch self {");
  out.push("    case .client(let c, _):");
  out.push("      prefix = \"QVAC client error \\(c.rawValue) (\\(c.wireName))\"");
  out.push("    case .server(let c, _):");
  out.push("      prefix = \"QVAC server error \\(c.rawValue) (\\(c.wireName))\"");
  out.push("    case .transport(let t):");
  out.push("      prefix = \"QVAC transport: \\(t.wireName)\"");
  out.push("    case .unknown(let code, let name, _):");
  out.push("      let codeStr = code.map { String($0) } ?? \"?\"");
  out.push("      prefix = \"QVAC unknown error \\(codeStr) (\\(name ?? \"-\"))\"");
  out.push("    }");
  out.push("    return \"\\(prefix): \\(self.message)\"");
  out.push("  }");
  out.push("}");
  out.push("");

  out.push("/// Numeric SDK client error codes from `@qvac/sdk` `SDK_CLIENT_ERROR_CODES`.");
  out.push("/// Range: 50,001–52,000. Pinned to the codegen package's npm version.");
  out.push(`/// Total cases at codegen time: ${sortedClient.length}`);
  out.push("public enum QVACClientErrorCode: Int, Sendable, Equatable, CaseIterable {");
  for (const [name, code] of sortedClient) {
    out.push(`  case ${snakeToLowerCamel(name)} = ${code}`);
  }
  out.push("");
  out.push("  /// JS-side enum key (SCREAMING_SNAKE_CASE) for cross-runtime debugging.");
  out.push("  public var wireName: String {");
  out.push("    switch self {");
  for (const [name] of sortedClient) {
    out.push(`    case .${snakeToLowerCamel(name)}: return "${name}"`);
  }
  out.push("    }");
  out.push("  }");
  out.push("}");
  out.push("");

  out.push("/// Numeric SDK server error codes from `@qvac/sdk` `SDK_SERVER_ERROR_CODES`.");
  out.push("/// Range: 52,001–54,000.");
  out.push(`/// Total cases at codegen time: ${sortedServer.length}`);
  out.push("public enum QVACServerErrorCode: Int, Sendable, Equatable, CaseIterable {");
  for (const [name, code] of sortedServer) {
    out.push(`  case ${snakeToLowerCamel(name)} = ${code}`);
  }
  out.push("");
  out.push("  /// JS-side enum key (SCREAMING_SNAKE_CASE) for cross-runtime debugging.");
  out.push("  public var wireName: String {");
  out.push("    switch self {");
  for (const [name] of sortedServer) {
    out.push(`    case .${snakeToLowerCamel(name)}: return "${name}"`);
  }
  out.push("    }");
  out.push("  }");
  out.push("}");
  out.push("");

  out.push("/// Transport-level errors local to the Swift client. Never serialized");
  out.push("/// on the wire — emitted when framing or codec layers fail before a");
  out.push("/// real error response can be exchanged.");
  out.push("public enum QVACTransportError: Sendable, Equatable {");
  out.push("  case transportClosed");
  out.push("  case framingError(String)");
  out.push("  case decodingFailed(String)");
  out.push("");
  out.push("  public var wireName: String {");
  out.push("    switch self {");
  out.push("    case .transportClosed: return \"TRANSPORT_CLOSED\"");
  out.push("    case .framingError: return \"FRAMING_ERROR\"");
  out.push("    case .decodingFailed: return \"DECODING_FAILED\"");
  out.push("    }");
  out.push("  }");
  out.push("");
  out.push("  public var message: String {");
  out.push("    switch self {");
  out.push("    case .transportClosed: return \"Transport closed unexpectedly\"");
  out.push("    case .framingError(let m): return \"Frame decoding failed: \\(m)\"");
  out.push("    case .decodingFailed(let m): return \"Payload decoding failed: \\(m)\"");
  out.push("    }");
  out.push("  }");
  out.push("}");

  const swiftPath = path.join(outDir, "ErrorCodes.swift");
  writeFileSync(swiftPath, out.join("\n") + "\n", "utf-8");

  // Sidecar JSON snapshot — Swift tests use this to verify the generated
  // Swift file matches the npm-package source-of-truth byte for byte.
  const meta = {
    source: `${input.packageName}@${input.packageVersion}`,
    clientCount: sortedClient.length,
    serverCount: sortedServer.length,
    clientCodes: Object.fromEntries(sortedClient),
    serverCodes: Object.fromEntries(sortedServer),
  };
  const metaPath = path.join(outDir, "ErrorCodes.json");
  writeFileSync(metaPath, JSON.stringify(meta, null, 2) + "\n", "utf-8");

  return {
    swiftPath,
    metaPath,
    clientCount: sortedClient.length,
    serverCount: sortedServer.length,
  };
}

function sortByCode(codes: Record<string, number>): Array<[string, number]> {
  return Object.entries(codes).sort((a, b) => {
    if (a[1] !== b[1]) return a[1] - b[1];
    return a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0;
  });
}
